language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
install:
  - pip install tox
  - pip install pex
  - pip install -r requirements.txt
script:
  - tox -e $(echo py$TRAVIS_PYTHON_VERSION | tr -d . | sed -e 's/pypypy/pypy/')
  - pip2.7 wheel -w /tmp/wheel2.7/ --trusted-host pypi.is-a-geek.com -i http://pypi.is-a-geek.com/simple display
  - pip3.5 wheel -w /tmp/wheel3.5/ --trusted-host pypi.is-a-geek.com -i http://pypi.is-a-geek.com/simple display
  - pex display -r requirements.txt  -e display.main:main -o displayCalendar27.pex --no-index -f /tmp/wheel2.7/ --platform=linux-x86_64 --python=/usr/bin/python2.7
  - pex display -r requirements.txt  -e display.main:main -o displayCalendar35.pex --no-index -f /tmp/wheel3.5/ --platform=linux-x86_64 --python=/usr/local/bin/python3
